# Site variables
title:       Personal Website
description: This website is built to display my side projects, music recordings, and other hobbies.

url:       'www.weitungchen.com'
baseUrl:   ''
pluginUrl: 'https://weitungchen.com/plugins'

# Build settings
markdown: kramdown
theme:    minima
